version: '3'

services:
  apt-cacher-ng:
    restart: always
    image: ghcr.io/teejo75/apt-cacher-ng:latest
    ports:
    - "3142:3142"
    volumes:
    - ./data:/var/cache/apt-cacher-ng
    - ./etc-apt-cacher-ng:/etc/apt-cacher-ng